{{- if .Values.deployment.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cnn-app-template.name" . }}
    chart: {{ include "cnn-app-template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    albIngressName: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.deployment.port }}
      protocol: TCP
      name: port
      targetPort: {{ .Values.deployment.port }}
  selector:
    appSelector: deployment-{{ .Release.Name }}
{{- end }}
