# Default values for cnn-app-template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployment:
  create: true
  healthcheck: /

image:
  url: quay.io/turner/simple-backend:1.0
  pullPolicy: IfNotPresent

logzio: stderr

monitoring:
  enabled: "true"
  kb_article: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8080

ingress:
  domain: cnnio.net
  name: ""
  certArn: arn:aws:acm:us-east-2:175259281135:certificate/b103d442-01f7-4aee-9d9b-dbe825977714
  path: /*
