{{- if .Values.deployment.create -}}
{{- $albIngressName := .Release.Name | default "default" -}}
{{- $fallbackName := printf "%s-%s-backend" .Release.Namespace .Values.ingress.type -}}
{{- $fallbackSelector := printf "%s-%s-backend" .Release.Namespace .Values.ingress.type -}}
{{- $appName := .Release.Name | default $fallbackName -}}
{{- $appSelector := .Release.Name | default $fallbackSelector -}}
{{- $port := .Values.deployment.port | default 8080 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cnn-app-template.name" . }}
    chart: {{ include "cnn-app-template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    albIngressName: {{ $albIngressName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ $port }}
      protocol: TCP
      name: port
      targetPort: {{ $port }}
  selector:
    appSelector: deployment-{{ $appSelector }}
{{- end }}
